name: Run twitter Bot
on:
  schedule:
    - cron: '20 0 1 * *' # Run every month 00:20
  push:
    branches:
      - master # run also on push
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name : Remove meta.json
        run : |
            rm -rf meta.json

      - name: Remove metadata from git 
      
        run : |
            git config --global user.email "skshitizraj@gmail.com"
            git config --global user.name "kshitijrajsharma"
            git add -u
            git commit -m "Remove Meta"
            git push --force
