name: Run twitter Bot
on:
  schedule:
    - cron: '0 */1 * * *' # Run every 1 hour
  push:
    branches:
      - master # run also on push
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name : Install necessary dependecies  
        run : 
          pip install -r requirements.txt
      - name : Run App 
        env: #assign variables 
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run:
          python app.py

      - name: add metadata to git 
      
        run : |
            git pull 
            git config --global user.email "skshitizraj@gmail.com"
            git config --global user.name "kshitijrajsharma"
            git add -f meta.json
            git commit -m "Updated Tweet Meta"
            git push
